### ISSUE TITLE
Can Spotty Oauth callback honour --advertiseaddr?

### ISSUE THREAD

**Issue by LeoBreebaart** [michaelherger/Spotty-Plugin#157]
I have been running LMS/Lyrion from within Docker (in bridged mode) for years. I never had any trouble getting Spotty to work, but recently I had to do a reinstall from scratch, and Spotty would no longer show up in the Spotify 'devices' for doing the initial authentication/authorisation connect.

I browsed through the issues here on GIthub and found the reference to @michaelherger's latest development version of the plugin from his own repository. I installed that, used the shiny new OAUTH button -- and everything is working beautifully again. Thanks!

However, it didn't immediately work out of the box because the OAUTH callback URL used by Spotify contains the internal container host, i.e. something like `http://172.20.0.2:9000`. After manually copying the callback URL, and substituting my host's _actual_ IP address, the authentication succeeded (if I do it quickly enough to not hit the timeout).

But I *had* been specifying that actual IP address with an `EXTRA_ARGS="--advertiseaddr=192.168.178.42"` option to the Lyrion container setup -- so I was wondering if it might not be an option for Spotty to obtain that IP address by itself and use it when connecting to Spotify?

Regards,

-- Leo

**Comment by michaelherger** [comment]
Hmm... that actually should be working that way. What LMS version are you using?

**Comment by LeoBreebaart** [comment]
I am using the most recent `lmscommunity/lyrionmusicserver:stable` container, which identifies as `Lyrion Music Server (v9.0.1, 1734365592, Tue Dec 17 03:48:42 UTC 2024) perl 5.036000 - x86_64-linux-gnu-thread-multi`.

My docker-compose.yml is 
```
  services:

    lms:
      container_name: lms
  #    image: lmscommunity/logitechmediaserver:stable
      image: lmscommunity/lyrionmusicserver:stable
      restart: unless-stopped
      ports:
        - 9000:9000/tcp
        - 9090:9090/tcp
        - 3483:3483/tcp
        - 3483:3483/udp
      volumes:
        - /data/lms-config:/config:rw
        - /library/music/:/music:ro
        - /hex/squeezebox-playlists:/playlist:rw
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
      environment:
        - PUID=666
        - PGID=2112
        - EXTRA_ARGS="--advertiseaddr=192.168.178.42"
```

As far as the Sounds plug-is concerned, I can try to play its sounds, and it goes through the motions, but I don't hear anything. No error message that I can see either.
